topology:
  cells:
    - name: "sakiladb"
      etcd:
        replicas: 3
      vtctld:
        replicas: 1
      vtgate:
        replicas: 3
      mysqlProtocol:
        enabled: true
        authType: "none"
      keyspaces:
        - name: "sakila"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 2
                - type: "rdonly"
                  vttablet:
                    replicas: 1
          vschema:
            initial: |-
              {
                "tables": {
                  "actor": {},
                  "address": {},
                  "category": {},
                  "city": {},
                  "country": {},
                  "customer": {},
                  "film": {},
                  "film_actor": {},                  
                  "film_category": {},
                  "film_text": {},
                  "inventory": {},
                  "language": {},
                  "payment": {},
                  "rental": {},
                  "staff": {},
                  "store": {}
                }
              }

jobs:
  - name: "create-customer-keyspace"
    kind: "vtctlclient"
    command: "CreateKeyspace -served_from='master:sakila,replica:sakila,rdonly:sakila' customer"

etcd:
  replicas: 3
  resources:

vtctld:
  serviceType: "NodePort"
  resources:

vtgate:
  serviceType: "NodePort"
  resources:

vttablet:
  mysqlSize: "prod"
  resources:
  mysqlResources:

vtworker:
  resources:

pmm:
  enabled: false

orchestrator:
  enabled: false
