topology:
  cells:
    - name: "sakiladb"
      etcd:
        replicas: 3
      vtctld:
        replicas: 1
      vtgate:
        replicas: 3
      mysqlProtocol:
        enabled: true
        authType: "none"
      keyspaces:
        - name: "sakila"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 2
                - type: "rdonly"
                  vttablet:
                    replicas: 1
          schema:
            postsplit: |-
              drop table customer;
              drop table payment;
              drop table rental;
        - name: "customer"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 2
                - type: "rdonly"
                  vttablet:
                    replicas: 1
jobs:
  - name: "cleanreadonly"
    kind: "vtctlclient"
    command: "SetShardTabletControl -blacklisted_tables=customer,payment,rental -remove sakila/0 rdonly"
  - name: "cleanreplica"
    kind: "vtctlclient"
    command: "SetShardTabletControl -blacklisted_tables=customer,payment,rental -remove sakila/0 replica"
  - name: "cleanmaster"
    kind: "vtctlclient"
    command: "SetShardTabletControl -blacklisted_tables=customer,payment,rental -remove sakila/0 master"

etcd:
  replicas: 3
  resources:

vtctld:
  serviceType: "NodePort"
  resources:

vtgate:
  serviceType: "NodePort"
  resources:

vttablet:
  mysqlSize: "prod"
  resources:
  mysqlResources:

vtworker:
  resources:

pmm:
  enabled: false

orchestrator:
  enabled: false
